### PR TITLE
New api version and functions

### PR DESCRIPTION
**Pull request by Rudy-Tmc**
Hi @stanislavulrych ,

I've updated the API version and added Tempo planner functions.
Hopefully you can integrate them in the main.

Kind regards
Rudy

### CODE REVIEW

**Comment by stanislavulrych** [comment]
Hi @Rudy-Tmc ,

thank you for the PR. I would like to include your changes. However, I have 2 notes:

1. You are changing Tempo API version from v3 to v4, which is not backward compatible, hence it would be good to leave the current v3 implementation and introduce v4 separately, so the developer can still use the version he wants to use. 
My suggestion would be to have client_v3.py with v3 and introduce client_v4.py with v4 (file with your updates). Like this, the previous functionality would still be available. v3 would be marked as deprecated in the library so to motivate the everybody to develop v4. What do you think?

3.  Why there is `from ast import And`? I do not see it used anywhere in the code.

Please let me know. Thank you.

**Comment by Rudy-Tmc** [comment]
Hi, 
1. I think that is a great idea. It keeps the library flexibel to use.
2. This was leftover from something I tried and forgot to remove it.

Do you want a new pull request or will you remove the lib yourself?

Rudy

**Comment by stanislavulrych** [comment]
If you do not mind, may I ask you to:

1. Copy your client.py as client_v4.py (name the class TempoV4) and leave client.py untouched.
2. Remove the mentioned import from the file?

I would the merge the PR and do necessary alignments afterwards.

Thanks!

**Comment by Rudy-Tmc** [comment]
I will do so in the next coming days.

**Comment by Rudy-Tmc** [comment]
I've created a new branch and a new pull request, so this one can be closed

**Pull request closed without merging**
